# Generated by Django 5.2.7 on 2025-11-10 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
